config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'players#players_by_seasons'
  get 'season', to: 'players#season'

  root to: 'players#players_by_seasons'

end

app/models/player.rb
class Player < ActiveRecord::Base
  scope :forward, -> {where(role: "Forward")}
  scope :defenceman, -> {where(role: "Defenceman")}
  scope :goalkeeper, -> {where(role: "Goaltender")}
  scope :season1718, -> {where(season: "18").order(caphit: :desc)}
  scope :season1819, -> {where(season: "19").order(caphit: :desc)}
  scope :season1920, -> {where(season: "20").order(caphit: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def players_by_seasons
  end

  def season
    @forwards = Player.where(season: params[:season], role: "Forward").order(caphit: :desc).page(params[:forward_page])
    @defencemans = Player.where(season: params[:season], role: "Defenceman").order(caphit: :desc).page(params[:defenceman_page])
    @goalkeepers= Player.where(season: params[:season], role: "Goaltender").order(caphit: :desc).page(params[:goalkeeper_page])
#    @players = Player.where(season: params[:season]).order(caphit: :desc).page(params[:player_page])
    @header = "Season 20#{params[:season].to_i-1} - 20#{params[:season]}"
  end

  private
    def player_params
      params.require(:player).permit(:forward_page, :defenceman_page, :goalkeeper_page, :season)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Freeagents
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        .col-lg-6.col-lg-offset-3.col-md-8.col-md-offset-3
          %h3 Unrestricted free angents NHL 2018-2020
      .row
        .col-lg-2.col-md-3
          .btn-group-vertical
            = link_to "Home", home_path, class:'btn btn-default'
            = link_to "UFA in 2017-2018", season_path(season: 18), class:'btn btn-default'
            = link_to "UFA in 2018-2019", season_path(season: 19), class:'btn btn-default'
            = link_to "UFA in 2019-2020", season_path(season: 20), class:'btn btn-default'
        .col-lg-10.col-md-9
          

          = yield

app/views/players/_seasonall.html.haml
%table.table.table-hover
  %thead
    %tr.danger
      %th= players.first.role.pluralize
    %tr
      %th Name
      %th Team
      %th Logo
      %th Cap Hit
  %tbody
    - players.each do |player|
      %tr
        %th= player.name
        %th= player.team.name
        %th 
          %img{src: player.team.image}
        %th= player.caphit

app/views/players/_seasontable.html.haml
%h4= role.pluralize
%table.table.table-hover
  %thead
    %tr
      %th Name
      %th Team
      %th Logo
      %th Cap Hit
  %tbody
    - players.each do |player|
      %tr
        %th= player.name
        %th= player.team_name
        %th 
          %img{src: player.team_logo}
        %th= player.caphit

app/views/players/players_by_seasons.html.haml
%p Welcome home!

app/views/players/season.html.haml
%h4= @header
-#["Forward", "Defenceman", "Goaltender"].each do |role|
= render partial: 'seasontable', locals: {players: @forwards, role: "Forward"}
= paginate @forwards, theme: 'twitter-bootstrap-3', param_name: "forward_page"
= render partial: 'seasontable', locals: {players: @defencemans, role: "Defenceman"}
= paginate @defencemans, theme: 'twitter-bootstrap-3', param_name: "defenceman_page"
= render partial: 'seasontable', locals: {players: @goalkeepers, role: "Goalkeeper"}
= paginate @goalkeepers, theme: 'twitter-bootstrap-3', param_name: "goalkeeper_page"

app/views/players/season1718.html.haml
%h4= @header
= render partial: 'seasonall', locals: {players: @forwards}
= paginate @forwards, theme: 'twitter-bootstrap-3', param_name: "forward_page"
= render partial: 'seasonall', locals: {players: @defencemans}
= paginate @defencemans, theme: 'twitter-bootstrap-3', param_name: "defenceman_page"
= render partial: 'seasonall', locals: {players: @goalkeepers}
= paginate @goalkeepers, theme: 'twitter-bootstrap-3', param_name: "goalkeeper_page"

app/views/players/season_head.html.haml
%h4= @header
= render partial: 'seasontable', locals: {players: @forwards, role: "Forward"}
= paginate @forwards, theme: 'twitter-bootstrap-3', param_name: "forward_page"
= render partial: 'seasontable', locals: {players: @defencemans, role: "Defenceman"}
= paginate @defencemans, theme: 'twitter-bootstrap-3', param_name: "defenceman_page"
= render partial: 'seasontable', locals: {players: @goalkeepers, role: "Goalkeeper"}
= paginate @goalkeepers, theme: 'twitter-bootstrap-3', param_name: "goalkeeper_page"